/**
 * Common airlines for flight forms (sorted by name when building selects).
 * value stored is IATA airline designator (2 letters, occasionally 3 for regional).
 */
window.AIRLINE_OPTIONS = [
  { n: 'Aegean Airlines', c: 'A3' },
  { n: 'Aer Lingus', c: 'EI' },
  { n: 'Aeroméxico', c: 'AM' },
  { n: 'Air Canada', c: 'AC' },
  { n: 'Air China', c: 'CA' },
  { n: 'Air France', c: 'AF' },
  { n: 'Air India', c: 'AI' },
  { n: 'Air New Zealand', c: 'NZ' },
  { n: 'AirAsia', c: 'AK' },
  { n: 'Alaska Airlines', c: 'AS' },
  { n: 'American Airlines', c: 'AA' },
  { n: 'ANA', c: 'NH' },
  { n: 'British Airways', c: 'BA' },
  { n: 'Cathay Pacific', c: 'CX' },
  { n: 'China Airlines', c: 'CI' },
  { n: 'China Eastern', c: 'MU' },
  { n: 'China Southern', c: 'CZ' },
  { n: 'Delta Air Lines', c: 'DL' },
  { n: 'easyJet', c: 'U2' },
  { n: 'EgyptAir', c: 'MS' },
  { n: 'Emirates', c: 'EK' },
  { n: 'Ethiopian Airlines', c: 'ET' },
  { n: 'Etihad Airways', c: 'EY' },
  { n: 'EVA Air', c: 'BR' },
  { n: 'Finnair', c: 'AY' },
  { n: 'Garuda Indonesia', c: 'GA' },
  { n: 'Gulf Air', c: 'GF' },
  { n: 'Hawaiian Airlines', c: 'HA' },
  { n: 'Iberia', c: 'IB' },
  { n: 'IndiGo', c: '6E' },
  { n: 'Japan Airlines', c: 'JL' },
  { n: 'Jetstar', c: 'JQ' },
  { n: 'Jetstar Asia', c: '3K' },
  { n: 'KLM', c: 'KL' },
  { n: 'Korean Air', c: 'KE' },
  { n: 'LATAM', c: 'LA' },
  { n: 'Lufthansa', c: 'LH' },
  { n: 'Malaysia Airlines', c: 'MH' },
  { n: 'Philippine Airlines', c: 'PR' },
  { n: 'Qantas', c: 'QF' },
  { n: 'Qatar Airways', c: 'QR' },
  { n: 'Ryanair', c: 'FR' },
  { n: 'SAS Scandinavian', c: 'SK' },
  { n: 'Saudia', c: 'SV' },
  { n: 'Scoot', c: 'TR' },
  { n: 'Singapore Airlines', c: 'SQ' },
  { n: 'Southwest Airlines', c: 'WN' },
  { n: 'Swiss', c: 'LX' },
  { n: 'TAP Air Portugal', c: 'TP' },
  { n: 'Thai Airways', c: 'TG' },
  { n: 'Turkish Airlines', c: 'TK' },
  { n: 'United Airlines', c: 'UA' },
  { n: 'VietJet Air', c: 'VJ' },
  { n: 'Vietnam Airlines', c: 'VN' },
  { n: 'Virgin Atlantic', c: 'VS' },
  { n: 'Virgin Australia', c: 'VA' },
  { n: 'WestJet', c: 'WS' },
];
